# API ENDPOINTS


# All Rated Extreme Demons List (AREDL)

AREDL_BASE_URL = "https://api.aredl.net/v2/api"

# CONFIGURACIONES TECNICAS

REQUEST_TIMEOUT = 10  # Tiempo de espera para las solicitudes HTTP en segundos

# CONFIGURACIONES DE LA LADDER

GAMEPLAY_WEIGHT = 5
VEHICLE_WEIGHT = 4
LENGTH_WEIGHT = 3
NERVE_CONTROL_WEIGHT = 3
VERSION_WEIGHT = 2